### ISSUE TITLE
Google Chrome Dependency

### ISSUE THREAD

**Issue by Segmentational** [maxtheaxe/discount-money-bot#1]
```
: python -m pip install --requirement Dependencies 
Requirement already satisfied: aiodns==2.0.0 in ./.venv/lib/python3.8/site-packages (from -r Dependencies (line 1)) (2.0.0)
Requirement already satisfied: aiohttp==3.7.3 in ./.venv/lib/python3.8/site-packages (from -r Dependencies (line 2)) (3.7.3)
Requirement already satisfied: aiohttp-socks==0.5.5 in ./.venv/lib/python3.8/site-packages (from -r Dependencies (line 3)) (0.5.5)
Requirement already satisfied: async-timeout==3.0.1 in ./.venv/lib/python3.8/site-packages (from -r Dependencies (line 4)) (3.0.1)
Requirement already satisfied: attrs==20.3.0 in ./.venv/lib/python3.8/site-packages (from -r Dependencies (line 5)) (20.3.0)
Requirement already satisfied: beautifulsoup4==4.9.3 in ./.venv/lib/python3.8/site-packages (from -r Dependencies (line 6)) (4.9.3)
Requirement already satisfied: cchardet==2.1.7 in ./.venv/lib/python3.8/site-packages (from -r Dependencies (line 7)) (2.1.7)
Requirement already satisfied: certifi==2020.12.5 in ./.venv/lib/python3.8/site-packages (from -r Dependencies (line 8)) (2020.12.5)
Requirement already satisfied: cffi==1.14.4 in ./.venv/lib/python3.8/site-packages (from -r Dependencies (line 9)) (1.14.4)
Requirement already satisfied: chardet==3.0.4 in ./.venv/lib/python3.8/site-packages (from -r Dependencies (line 10)) (3.0.4)
Requirement already satisfied: elasticsearch==7.10.1 in ./.venv/lib/python3.8/site-packages (from -r Dependencies (line 11)) (7.10.1)
Requirement already satisfied: fake-useragent==0.1.11 in ./.venv/lib/python3.8/site-packages (from -r Dependencies (line 12)) (0.1.11)
Requirement already satisfied: geographiclib==1.50 in ./.venv/lib/python3.8/site-packages (from -r Dependencies (line 13)) (1.50)
Requirement already satisfied: geopy==2.1.0 in ./.venv/lib/python3.8/site-packages (from -r Dependencies (line 14)) (2.1.0)
Requirement already satisfied: googletransx==2.4.2 in ./.venv/lib/python3.8/site-packages (from -r Dependencies (line 15)) (2.4.2)
Requirement already satisfied: idna==3.0 in ./.venv/lib/python3.8/site-packages (from -r Dependencies (line 16)) (3.0)
Requirement already satisfied: multidict==5.1.0 in ./.venv/lib/python3.8/site-packages (from -r Dependencies (line 17)) (5.1.0)
Requirement already satisfied: numpy==1.19.4 in ./.venv/lib/python3.8/site-packages (from -r Dependencies (line 18)) (1.19.4)
Requirement already satisfied: pandas==1.2.0 in ./.venv/lib/python3.8/site-packages (from -r Dependencies (line 19)) (1.2.0)
Requirement already satisfied: pycares==3.1.1 in ./.venv/lib/python3.8/site-packages (from -r Dependencies (line 20)) (3.1.1)
Requirement already satisfied: pycparser==2.20 in ./.venv/lib/python3.8/site-packages (from -r Dependencies (line 21)) (2.20)
Requirement already satisfied: PySocks==1.7.1 in ./.venv/lib/python3.8/site-packages (from -r Dependencies (line 22)) (1.7.1)
Requirement already satisfied: python-dateutil==2.8.1 in ./.venv/lib/python3.8/site-packages (from -r Dependencies (line 23)) (2.8.1)
Requirement already satisfied: python-socks==1.1.2 in ./.venv/lib/python3.8/site-packages (from -r Dependencies (line 24)) (1.1.2)
Requirement already satisfied: pytz==2020.5 in ./.venv/lib/python3.8/site-packages (from -r Dependencies (line 25)) (2020.5)
Requirement already satisfied: requests==2.25.1 in ./.venv/lib/python3.8/site-packages (from -r Dependencies (line 26)) (2.25.1)
Requirement already satisfied: schedule==0.6.0 in ./.venv/lib/python3.8/site-packages (from -r Dependencies (line 27)) (0.6.0)
Requirement already satisfied: selenium==3.141.0 in ./.venv/lib/python3.8/site-packages (from -r Dependencies (line 28)) (3.141.0)
Requirement already satisfied: six==1.15.0 in ./.venv/lib/python3.8/site-packages (from -r Dependencies (line 29)) (1.15.0)
Requirement already satisfied: soupsieve==2.1 in ./.venv/lib/python3.8/site-packages (from -r Dependencies (line 30)) (2.1)
Requirement already satisfied: twint==2.1.20 in ./.venv/lib/python3.8/site-packages (from -r Dependencies (line 31)) (2.1.20)
Requirement already satisfied: typing-extensions==3.7.4.3 in ./.venv/lib/python3.8/site-packages (from -r Dependencies (line 32)) (3.7.4.3)
Requirement already satisfied: urllib3==1.26.2 in ./.venv/lib/python3.8/site-packages (from -r Dependencies (line 33)) (1.26.2)
Requirement already satisfied: yarl==1.6.3 in ./.venv/lib/python3.8/site-packages (from -r Dependencies (line 34)) (1.6.3)
Requirement already satisfied: chromedriver_autoinstaller in ./.venv/lib/python3.8/site-packages (from -r Dependencies (line 35)) (0.2.2)
Requirement already satisfied: playsound in ./.venv/lib/python3.8/site-packages (from -r Dependencies (line 36)) (1.2.2)
INFO: pip is looking at multiple versions of pytz to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of python-socks to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of python-dateutil to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of pysocks to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of pycparser to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of pycares to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of pandas to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of numpy to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of multidict to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of idna to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of googletransx to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of geopy to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of geographiclib to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of fake-useragent to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of elasticsearch to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of chardet to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of cffi to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of certifi to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of cchardet to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of beautifulsoup4 to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of attrs to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of async-timeout to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of aiohttp-socks to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of aiohttp to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of aiodns to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install idna==3.0 and requests==2.25.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested idna==3.0
    requests 2.25.1 depends on idna<3 and >=2.5

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
(.venv) (Byte) [6.8%][4.05G/32.76G] 01/01/21 10:54 AM
   ﬌ [  ] /opt/Development/Repositories/Infrastructure/discount-money-bot
: python -m pip install --requirement Dependencies 
Requirement already satisfied: aiodns==2.0.0 in ./.venv/lib/python3.8/site-packages (from -r Dependencies (line 1)) (2.0.0)
Requirement already satisfied: aiohttp==3.7.3 in ./.venv/lib/python3.8/site-packages (from -r Dependencies (line 2)) (3.7.3)
Requirement already satisfied: aiohttp-socks==0.5.5 in ./.venv/lib/python3.8/site-packages (from -r Dependencies (line 3)) (0.5.5)
Requirement already satisfied: async-timeout==3.0.1 in ./.venv/lib/python3.8/site-packages (from -r Dependencies (line 4)) (3.0.1)
Requirement already satisfied: attrs==20.3.0 in ./.venv/lib/python3.8/site-packages (from -r Dependencies (line 5)) (20.3.0)
Requirement already satisfied: beautifulsoup4==4.9.3 in ./.venv/lib/python3.8/site-packages (from -r Dependencies (line 6)) (4.9.3)
Requirement already satisfied: cchardet==2.1.7 in ./.venv/lib/python3.8/site-packages (from -r Dependencies (line 7)) (2.1.7)
Requirement already satisfied: certifi==2020.12.5 in ./.venv/lib/python3.8/site-packages (from -r Dependencies (line 8)) (2020.12.5)
Requirement already satisfied: cffi==1.14.4 in ./.venv/lib/python3.8/site-packages (from -r Dependencies (line 9)) (1.14.4)
Requirement already satisfied: chardet==3.0.4 in ./.venv/lib/python3.8/site-packages (from -r Dependencies (line 10)) (3.0.4)
Requirement already satisfied: elasticsearch==7.10.1 in ./.venv/lib/python3.8/site-packages (from -r Dependencies (line 11)) (7.10.1)
Requirement already satisfied: fake-useragent==0.1.11 in ./.venv/lib/python3.8/site-packages (from -r Dependencies (line 12)) (0.1.11)
Requirement already satisfied: geographiclib==1.50 in ./.venv/lib/python3.8/site-packages (from -r Dependencies (line 13)) (1.50)
Requirement already satisfied: geopy==2.1.0 in ./.venv/lib/python3.8/site-packages (from -r Dependencies (line 14)) (2.1.0)
Requirement already satisfied: googletransx==2.4.2 in ./.venv/lib/python3.8/site-packages (from -r Dependencies (line 15)) (2.4.2)
Requirement already satisfied: multidict==5.1.0 in ./.venv/lib/python3.8/site-packages (from -r Dependencies (line 16)) (5.1.0)
Requirement already satisfied: numpy==1.19.4 in ./.venv/lib/python3.8/site-packages (from -r Dependencies (line 17)) (1.19.4)
Requirement already satisfied: pandas==1.2.0 in ./.venv/lib/python3.8/site-packages (from -r Dependencies (line 18)) (1.2.0)
Requirement already satisfied: pycares==3.1.1 in ./.venv/lib/python3.8/site-packages (from -r Dependencies (line 19)) (3.1.1)
Requirement already satisfied: pycparser==2.20 in ./.venv/lib/python3.8/site-packages (from -r Dependencies (line 20)) (2.20)
Requirement already satisfied: PySocks==1.7.1 in ./.venv/lib/python3.8/site-packages (from -r Dependencies (line 21)) (1.7.1)
Requirement already satisfied: python-dateutil==2.8.1 in ./.venv/lib/python3.8/site-packages (from -r Dependencies (line 22)) (2.8.1)
Requirement already satisfied: python-socks==1.1.2 in ./.venv/lib/python3.8/site-packages (from -r Dependencies (line 23)) (1.1.2)
Requirement already satisfied: pytz==2020.5 in ./.venv/lib/python3.8/site-packages (from -r Dependencies (line 24)) (2020.5)
Requirement already satisfied: schedule==0.6.0 in ./.venv/lib/python3.8/site-packages (from -r Dependencies (line 25)) (0.6.0)
Requirement already satisfied: selenium==3.141.0 in ./.venv/lib/python3.8/site-packages (from -r Dependencies (line 26)) (3.141.0)
Requirement already satisfied: six==1.15.0 in ./.venv/lib/python3.8/site-packages (from -r Dependencies (line 27)) (1.15.0)
Requirement already satisfied: soupsieve==2.1 in ./.venv/lib/python3.8/site-packages (from -r Dependencies (line 28)) (2.1)
Requirement already satisfied: twint==2.1.20 in ./.venv/lib/python3.8/site-packages (from -r Dependencies (line 29)) (2.1.20)
Requirement already satisfied: typing-extensions==3.7.4.3 in ./.venv/lib/python3.8/site-packages (from -r Dependencies (line 30)) (3.7.4.3)
Requirement already satisfied: urllib3==1.26.2 in ./.venv/lib/python3.8/site-packages (from -r Dependencies (line 31)) (1.26.2)
Requirement already satisfied: yarl==1.6.3 in ./.venv/lib/python3.8/site-packages (from -r Dependencies (line 32)) (1.6.3)
Requirement already satisfied: idna in ./.venv/lib/python3.8/site-packages (from -r Dependencies (line 34)) (3.0)
Requirement already satisfied: requests in ./.venv/lib/python3.8/site-packages (from -r Dependencies (line 35)) (2.25.1)
Requirement already satisfied: chromedriver_autoinstaller in ./.venv/lib/python3.8/site-packages (from -r Dependencies (line 36)) (0.2.2)
Requirement already satisfied: playsound in ./.venv/lib/python3.8/site-packages (from -r Dependencies (line 37)) (1.2.2)
Collecting idna
  Using cached idna-2.10-py2.py3-none-any.whl (58 kB)
Installing collected packages: idna
  Attempting uninstall: idna
    Found existing installation: idna 3.0
    Uninstalling idna-3.0:
      Successfully uninstalled idna-3.0
Successfully installed idna-2.10
(.venv) (Byte) [4.8%][4.00G/32.76G] 01/01/21 10:55 AM
   ﬌ [  ] /opt/Development/Repositories/Infrastructure/discount-money-bot
: python -m Bot

        --- Discount Money Bot by Max ---

        Warning: Use this program at your own risk!
        (press Enter to continue)
        
        Enter your first name for checkout purposes
        (press Enter to continue)

        Jacob

        Enter your last name for checkout purposes
        (press Enter to continue)

        Sanders

        Enter your venmo username for checkout purposes
        (press Enter to continue)

        jsanders4129

        Enter your email for checkout purposes
        (press Enter to continue)

        jsanders4129@gmail.com

        Please confirm your details:


        First Name:  Jacob 


        Last Name:  Sanders 


        Venmo Username:  jsanders4129 


        Email Address:  jsanders4129@gmail.com 

        Are these details correct?
        (press 'Y' to continue, or 'N' to retry, followed by [Enter])

        y
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/Development/Repositories/Infrastructure/discount-money-bot/Bot/__main__.py", line 11, in <module>
    main()
  File "/opt/Development/Repositories/Infrastructure/discount-money-bot/Bot/__main__.py", line 8, in main
    Minion.main()
  File "/opt/Development/Repositories/Infrastructure/discount-money-bot/Bot/Minion.py", line 313, in main
    driver = launch()
  File "/opt/Development/Repositories/Infrastructure/discount-money-bot/Bot/Minion.py", line 51, in launch
    driver = start_driver(headless)  # start the driver and store it (will be returned)
  File "/opt/Development/Repositories/Infrastructure/discount-money-bot/Bot/Minion.py", line 116, in start_driver
    cda.install()
  File "/opt/Development/Repositories/Infrastructure/discount-money-bot/.venv/lib/python3.8/site-packages/chromedriver_autoinstaller/__init__.py", line 15, in install
    chromedriver_filepath = utils.download_chromedriver(cwd)
  File "/opt/Development/Repositories/Infrastructure/discount-money-bot/.venv/lib/python3.8/site-packages/chromedriver_autoinstaller/utils.py", line 166, in download_chromedriver
    chrome_version = get_chrome_version()
  File "/opt/Development/Repositories/Infrastructure/discount-money-bot/.venv/lib/python3.8/site-packages/chromedriver_autoinstaller/utils.py", line 110, in get_chrome_version
    process = subprocess.Popen(['/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', '--version'], stdout=subprocess.PIPE)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'
```

**Comment by Segmentational** [comment]
To be specific, I would remove any dependency associated with the user's web-browser; rather, just use whatever they have set to their default. This can be completed all via Python built-ins: https://docs.python.org/3/library/webbrowser.html

However, and admittedly, it may not be applicable with this program as I'm unsure what other dependencies there may be.

**Comment by maxtheaxe** [comment]
The reason it's checking to see if you have Chrome installed is because it's set up to automatically download the correct version of ChromeDriver (which is separate from the average user's Chrome installation) and/or give Selenium its installation path.

It would probably be fairly easy for me to work in Firefox (AKA GeckoDriver) compatibility, which would tend to be my first choice, considering that Firefox is the browser I actually use on a daily basis. In the past, I've had issues with GeckoDriver functioning perfectly with Selenium, but I'm willing to take another crack at it.

As for Safari, Apple has deprecated SafariDriver (not to mention the fact that, as a Windows user, I have no good way of testing that), and [its usage with Selenium now requires the installation of an additional extension](https://www.edureka.co/community/46309/possible-selenium-automation-scripts-browser-windows-machine) (which I've also never worked with before). Simply, I figured enough people have Chrome, that, for a quick project (with a limited lifespan), it'd be okay. I'll do more exploration of Selenium with Safari for future projects.

Unfortunately, I know nothing about other browsers and their usage with Selenium. I'll do some reading for future projects.

At a minimum, I should handle that error you got and give something readable to the user, and tell them they have to install Chrome (or Firefox, if I add that) in order for the bot to function. I'm surprised that the library I'm using to handle the ChromeDriver download doesn't already do that itself, but oh well.

**Comment by maxtheaxe** [comment]
Considering that the popup shop has been closed, instead of adding wider browser compatibility (i.e. Firefox/Gecko) to this now-useless project, I will instead keep this in mind and try to do so on future Selenium-based projects.
